### ISSUE TITLE
Оформление для статистики

### ISSUE THREAD

**Issue by catindev** [exoriri/ms-graphics#8]
1) Страница с графиком 
![image](https://user-images.githubusercontent.com/2453616/33797785-2211320a-dd38-11e7-92c9-ccc3722eb1b7.png)

2) Страница с цифрами. Фикс — если у такой страницы есть интервал, то без селекта с типом интервала
![image](https://user-images.githubusercontent.com/2453616/33797899-e8a7dd46-dd39-11e7-86c9-72ed6f5aba01.png)

3) Скрывать датапикер после выбора дат. Задаётся настройкой _autoClose: true_

**Comment by catindev** [comment]
Поправить:
![image](https://user-images.githubusercontent.com/2453616/33805168-61bb60dc-ddde-11e7-82de-3249aa7985eb.png)

1. Убрать нижнюю рамку у хэдера
2. Подменю к левому краю, не по центру
3. Цифры сделать как на макете и тоже к левому краю. Вообще весь контент по левому краю
4. Поставить прелоадер http://mindsales-crm.com/assets/images/loader80.gif
5. Базовые настройки шрифта:
```
font-family: -apple-system, BlinkMacSystemFont, Roboto, 'Segoe UI', 'Segoe WP', 'Helvetica Neue', 'Lucida Grande', Verdana, Tahoma, Arial, sans-serif !important;
color: #353B3F;
```

**Comment by catindev** [comment]
![image](https://user-images.githubusercontent.com/2453616/33815146-61479c62-de59-11e7-8aa0-4376e9bd5732.png)
1. Прямоугольниками отметил места с большими отступами. Убрать
2. Выровнять заголовок и сайдбар по крайней левой. Сайдбар и табы по верхней


![image](https://user-images.githubusercontent.com/2453616/33815208-e62bb1a2-de59-11e7-819c-e5cc16d28a69.png)
1. Убрать заголовок из графика
2. График по левому краю


![image](https://user-images.githubusercontent.com/2453616/33815254-25c8d434-de5a-11e7-993d-93979ea140e7.png)
Отступы снова марджинами делаешь. Это неправильно — твои блоки толкаются от родителя. Поправь. Должен быть паддинг у контейнера content который задаст отступы для всех внутренних блоков.


![image](https://user-images.githubusercontent.com/2453616/33815453-b41b5210-de5b-11e7-9f6d-0d184a15d5c3.png)
Зачем каждый элемент списка поменю завёрнут в div?


![image](https://user-images.githubusercontent.com/2453616/33815427-7dced04c-de5b-11e7-96ba-4c3a348eb098.png)
Правильно понимаю, что оформление графиков захардкожено в коде? Если, да то поправь. Должно приходить из АПИ.


![image](https://user-images.githubusercontent.com/2453616/33815304-7cf2505a-de5a-11e7-8548-6ab871423de2.png)
Интервал не оформлен

Баг — кликаю между пунктами подменю и пропадает контент страницы
https://monosnap.com/file/zJsjxsyk5JoaKrzh8QULKLLhOoctF6

**Comment by exoriri** [comment]
Каждый элемент завернут в див для того чтобы находить к какому из пунктов относится те или иные элементы и отображать их при нажатии.(Просто сделал решение которое в голову пришло). А вот в гистограмме будет только два столбца или может быть больше? Если только два и данные будут приходить в моем формате,то норм будет работать. А вот цвет да надо поменять там хардкод.

**Comment by catindev** [comment]
Имеешь ввиду только ли по два столбца в гистограмме? Нет. Количество может быть разным. Расскажи что от этого поменяется и какие сложности появятся

**Comment by catindev** [comment]
Пример со столбцами - графики эффективности рекламных номеров. Каждый столбик это номер. А номеров у клиентов может быть разное количество.

**Comment by exoriri** [comment]
да не ничего особо не изменится, просто надо по массиву пройтись и вставлять данные

**Comment by catindev** [comment]
А зачем тебе по нему проходиться? я сразу буду в нужном формате отправлять. Сделай несколько графиков-гистограмм и в фейковых АПИ сразу данные в формате твоей библиотеки отправляй
